// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhb-ay6-yn4xU5d7Xnktgp250eN6RYjIk',
    appId: '1:518009365052:web:ac39692ce97fcde52a9939',
    messagingSenderId: '518009365052',
    projectId: 'twitter-clone-d9b35',
    authDomain: 'twitter-clone-d9b35.firebaseapp.com',
    storageBucket: 'twitter-clone-d9b35.firebasestorage.app',
    measurementId: 'G-3VNRCGJ4FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4v0ecGxfJYGQOBG2jP4WHO_e_CK6HLiE',
    appId: '1:518009365052:android:59e8b237d4a7dc0b2a9939',
    messagingSenderId: '518009365052',
    projectId: 'twitter-clone-d9b35',
    storageBucket: 'twitter-clone-d9b35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA-8IcGzn-9ljxOjwvkMeG-Daemxo2ZjE',
    appId: '1:518009365052:ios:773dad9c4fae85b82a9939',
    messagingSenderId: '518009365052',
    projectId: 'twitter-clone-d9b35',
    storageBucket: 'twitter-clone-d9b35.firebasestorage.app',
    iosBundleId: 'com.example.twitterCloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA-8IcGzn-9ljxOjwvkMeG-Daemxo2ZjE',
    appId: '1:518009365052:ios:773dad9c4fae85b82a9939',
    messagingSenderId: '518009365052',
    projectId: 'twitter-clone-d9b35',
    storageBucket: 'twitter-clone-d9b35.firebasestorage.app',
    iosBundleId: 'com.example.twitterCloneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhb-ay6-yn4xU5d7Xnktgp250eN6RYjIk',
    appId: '1:518009365052:web:dfa270efa01313a42a9939',
    messagingSenderId: '518009365052',
    projectId: 'twitter-clone-d9b35',
    authDomain: 'twitter-clone-d9b35.firebaseapp.com',
    storageBucket: 'twitter-clone-d9b35.firebasestorage.app',
    measurementId: 'G-3RSXEMMJV5',
  );

}